object Versions {
    const val koin = "3.1.5"
    const val kotlin = "1.6.10"
    const val gradle = "7.1.1"
    const val appCompat = "1.3.1"
    const val coreKtx = "1.6.0"
    const val constraintLayout = "2.1.0"
    const val material = "1.4.0"
    const val retrofit = "2.9.0"
    const val okHttp = "4.9.0"
    const val gson = "2.8.6"
    const val picasso = "2.71828"
    const val junit = "4.13"
    const val junitExt = "1.1.3"
    const val mockk = "1.12.2"
    const val testRunner = "1.4.0"
    const val espresso = "3.4.0"
    const val lifecycle = "2.3.1"
    const val coroutines = "1.3.9"
    const val room = "2.4.1"
    const val navigation = "2.4.1"
    const val lottie = "4.2.2"

}